"""empty message

Revision ID: 32d910c61aaa
Revises: f412434b3ca6
Create Date: 2017-07-05 14:55:08.961389

"""

# revision identifiers, used by Alembic.
revision = '32d910c61aaa'
down_revision = 'f412434b3ca6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('target_table', sa.String(length=200), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'collection', sa.Column('name', sa.String(length=999), nullable=True))
    op.drop_column(u'collection', 'target_id')
    op.drop_column(u'collection', 'order')
    op.drop_column(u'collection', 'target_table')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'collection', sa.Column('target_table', mysql.VARCHAR(length=200), nullable=True))
    op.add_column(u'collection', sa.Column('order', mysql.VARCHAR(length=100), nullable=True))
    op.add_column(u'collection', sa.Column('target_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column(u'collection', 'name')
    op.drop_table('collection_items')
    ### end Alembic commands ###
