version: '2'
services:
  proxy:
    build: ./proxy
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/matthew-lavin.conf

  matthew-lavin:
    build: ./matthew-lavin
    container_name: matthew-lavin

  thedatahumanist:
    build: ./thedatahumanist
    container_name: thedatahumanist

  humanitiesdata:
    build: ./humanitiesdata
    container_name: humanitiesdata
  flask_db:
    build: ./mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQLPASS}"

  digiped_fall_2016:
    build: ./digiped_fall_2016
    container_name: digiped_fall_2016
    links:
      - flask_db:mysql
    ports:
      - 8080:80
