version: '2'
services:
  proxy:
    build: ./proxy
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/apps/proxy/nginx.conf:/etc/nginx/conf.d/matthew-lavin.conf

    links:
      - flask_base
      - humanitiesdata
      - matthew-lavin
      - digiped_fall_2016
      - acdm_spring_2017
      - nt_spring_2017
      - neo_web_app
      - nyt_web_app
      - compvolution
      - faculty_activity
      - mtb_fall_2017
      - cdm_spring_2018
      - mtb_spring_2018
      - mtb_fall_2018
      - dh_fall_2018
      - pdc_spring_2019
      - arm_fall_2019
      - rebeccamlee

  flask_base:
    build: ./flaskbase
    container_name: flask_empty
    image: lavinflaskbase

  flask_base_2019:
    build: ./flaskbase-2019
    container_name: flask_empty_2019
    image: lavinflaskbase_2019

  faculty_activity:
    build: ./faculty-activity
    container_name: faculty_activity
    links:
      - flask_base

  compvolution:
    build: ./compvolution
    container_name: compvolution
    links:
      - flask_base

  rebeccamlee:
    build: ./rebeccamlee
    container_name: rebeccamlee
    links:
      - flask_base_2019

  matthew-lavin:
    build: ./matthew-lavin
    container_name: matthew-lavin
    links: 
      - flask_base_2019

  humanitiesdata:
    build: ./humanitiesdata
    container_name: humanitiesdata
    links:
      - flask_base

  neo_web_app:
    build: ./neo_web_app
    container_name: neo_web_app
    links:
      - flask_base

  nyt_web_app:
    build: ./nyt_web_app
    container_name: nyt_web_app
    links:
      - flask_base

  digiped_fall_2016:
    build: ./courses/digiped_fall_2016
    container_name: digiped_fall_2016
    links:
      - flask_base

  acdm_spring_2017:
    build: ./courses/acdm_spring_2017
    container_name: acdm_spring_2017
    links:
      - flask_base

  nt_spring_2017:
    build: ./courses/nt_spring_2017
    container_name: nt_spring_2017
    links:
      - flask_base

  mtb_fall_2017:
    build: ./courses/mtb_fall_2017
    container_name: mtb_fall_2017
    links:
      - flask_base

  cdm_spring_2018:
    build: ./courses/cdm_spring_2018
    container_name: cdm_spring_2018
    links:
      - flask_base

  mtb_spring_2018:
    build: ./courses/mtb_spring_2018
    container_name: mtb_spring_2018
    links:
      - flask_base
 
  mtb_fall_2018:
    build: ./courses/mtb_fall_2018
    container_name: mtb_fall_2018
    volumes:
      - ./courses/mtb_fall_2018/app/templates:/app/templates
      - ./courses/mtb_fall_2018/app/static:/app/static
    links:
      - flask_base

  dh_fall_2018:
    build: ./courses/dh_fall_2018
    container_name: dh_fall_2018
    volumes:
      - ./courses/dh_fall_2018/app/templates:/app/templates
      - ./courses/dh_fall_2018/app/static:/app/static
    links:
      - flask_base

  pdc_spring_2019:
    build: ./courses/pdc_spring_2019
    container_name: pdc_spring_2019
    volumes:
      - ./courses/pdc_spring_2019/app/templates:/app/templates
      - ./courses/pdc_spring_2019/app/static:/app/static
    links:
      - flask_base_2019

  pdc_spring_2019:
    build: ./courses/arm_fall_2019
    container_name: arm_fall_2019
    volumes:
      - ./courses/arm_fall_2019/app/templates:/app/templates
      - ./courses/arm_fall_2019/app/static:/app/static
    links:
      - flask_base_2019
