version: '2'
services:
  proxy:
    build: ./proxy
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/apps/proxy/nginx.conf:/etc/nginx/conf.d/matthew-lavin.conf

    links:
      - flask_base_2024
      - flask_base_2019
      - humanitiesdata
      - humanities_analytics
      - matthew-lavin
      - rebeccamlee
      - nyt_web_app
      - aps_web_app
      - audiobooks_web_app

  flask_base_2019:
    build: ./flaskbase-2019
    container_name: flask_empty_2019
    image: lavinflaskbase_2019

  flask_base_2024:
    build: ./flaskbase-2024
    container_name: flask_empty_2024
    image: lavinflaskbase_2024 

  rebeccamlee:
    build: ./rebeccamlee
    container_name: rebeccamlee
    links:
      - flask_base_2019

  matthew-lavin:
    build: ./matthew-lavin
    container_name: matthew-lavin
    links: 
      - flask_base_2019

  humanitiesdata:
    build: ./humanitiesdata
    container_name: humanitiesdata
    links:
      - flask_base_2019

  humanities_analytics:
    build: ./humanities_analytics
    container_name: humanities_analytics
    links:
      - flask_base_2019

  nyt_web_app:
    build: ./nyt_web_app
    container_name: nyt_web_app
    links:
      - flask_base_2024
  
  aps_web_app:
    build: ./aps_web_app
    container_name: aps_web_app
    volumes:
      - ./aps_web_app/app/static:/app/static
    links:
      - flask_base_2024

  audiobooks_web_app:
    build: ./audiobooks_web_app
    container_name: audiobooks_web_app
    volumes:
      - ./audiobooks_web_app/app/static:/app/static
    links:
      - flask_base_2024

