version: '2'
services:
  proxy:
    build: ./proxy
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/matthew-lavin.conf

  flask_base:
    build: ./flaskbase
    container_name: flask_empty
    image: lavinflaskbase

  matthew-lavin:
    build: ./matthew-lavin
    container_name: matthew-lavin

  thedatahumanist:
    build: ./thedatahumanist
    container_name: thedatahumanist

  humanitiesdata:
    build: ./humanitiesdata
    container_name: humanitiesdata
    links:
      - flask_base

  digiped_fall_2016:
    build: ./courses/digiped_fall_2016
    container_name: digiped_fall_2016
    links:
      - flask_base

  acdm_spring_2017:
    build: ./courses/acdm_spring_2017
    container_name: acdm_spring_2017
    links:
      - flask_base

  nt_spring_2017:
    build: ./courses/nt_spring_2017
    container_name: nt_spring_2017
    links:
      - flask_base
