"""empty message

Revision ID: ac78eb02cfe9
Revises: 
Create Date: 2024-04-27 13:40:51.932402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac78eb02cfe9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_book_features',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('main_id', sa.Integer(), nullable=True),
    sa.Column('main_asin', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['main_id'], ['main._id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id')
    )
    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_genre_name'), ['name'], unique=False)

    with op.batch_alter_table('narrator', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_narrator_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('narrator', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_narrator_name'))

    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genre_name'))

    op.drop_table('audio_book_features')
    # ### end Alembic commands ###
