"""empty message

Revision ID: 3ebcd41fa74b
Revises: 0e9a23a6cbb4
Create Date: 2018-12-14 18:16:19.250397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ebcd41fa74b'
down_revision = '0e9a23a6cbb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_items')
    op.drop_table('collection')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=999), nullable=False),
    sa.Column('public', mysql.VARCHAR(length=128), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], name='collection_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('collection_items',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('collection_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('target_table', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('target_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('order', mysql.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], name='collection_items_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
