"""empty message

Revision ID: 8a9259a36a62
Revises: 3ebcd41fa74b
Create Date: 2018-12-14 18:28:12.946808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a9259a36a62'
down_revision = '3ebcd41fa74b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity', 'public',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('blog_post', 'public',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('dataset', 'field_notes',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('dataset', 'public',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('reading', 'public',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('tag', 'public',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('user_profile', 'custom_blog_path',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'custom_blog_path',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
    op.alter_column('tag', 'public',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('reading', 'public',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('dataset', 'public',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('dataset', 'field_notes',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('blog_post', 'public',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('activity', 'public',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###
