"""empty message

Revision ID: 9042c729998d
Revises: 8a9259a36a62
Create Date: 2018-12-14 18:31:13.139073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9042c729998d'
down_revision = '8a9259a36a62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('basics', 'course_description',
               existing_type=mysql.VARCHAR(length=9999),
               nullable=True)
    op.alter_column('blog_post', 'post_path',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
    op.alter_column('tag', 'tag_path',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'tag_path',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
    op.alter_column('blog_post', 'post_path',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
    op.alter_column('basics', 'course_description',
               existing_type=mysql.VARCHAR(length=9999),
               nullable=False)
    # ### end Alembic commands ###
