"""empty message

Revision ID: cafd5f979022
Revises: 420d5fb9ce53
Create Date: 2018-12-01 18:49:46.564039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cafd5f979022'
down_revision = '420d5fb9ce53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'custom_blog_title',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'custom_blog_title',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
