"""empty message

Revision ID: eade3461afd3
Revises: e8c5cd09ecab
Create Date: 2016-11-12 20:46:18.079119

"""

# revision identifiers, used by Alembic.
revision = 'eade3461afd3'
down_revision = 'e8c5cd09ecab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instructor', sa.String(length=128), nullable=True),
    sa.Column('office', sa.String(length=128), nullable=True),
    sa.Column('office_hours', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('course_name', sa.String(length=512), nullable=True),
    sa.Column('semester_year', sa.String(length=128), nullable=True),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('institution', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('basics')
    ### end Alembic commands ###
