"""empty message

Revision ID: 050f6b16fcd8
Revises: ad6aee010c53
Create Date: 2018-04-11 11:18:59.124242

"""

# revision identifiers, used by Alembic.
revision = '050f6b16fcd8'
down_revision = 'ad6aee010c53'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metadata', sa.Column('nyt_pdf_endpoint', sa.String(length=500), nullable=True))
    op.add_column('metadata', sa.Column('perceived_author_gender', sa.String(length=99), nullable=True))
    op.add_column('metadata', sa.Column('perceived_author_name', sa.String(length=99), nullable=True))
    op.add_column('metadata', sa.Column('reviewed_work_title', sa.String(length=500), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metadata', 'reviewed_work_title')
    op.drop_column('metadata', 'perceived_author_name')
    op.drop_column('metadata', 'perceived_author_gender')
    op.drop_column('metadata', 'nyt_pdf_endpoint')
    ### end Alembic commands ###
