"""empty message

Revision ID: 151c1574521e
Revises: 80112f16aa04
Create Date: 2019-02-24 13:35:15.121847

"""

# revision identifiers, used by Alembic.
revision = '151c1574521e'
down_revision = '80112f16aa04'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster_meta', sa.Column('full_text', sa.String(length=99999), nullable=True))
    op.drop_column('cluster_meta', 'corrected_transcription')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster_meta', sa.Column('corrected_transcription', mysql.MEDIUMTEXT(collation=u'utf8_bin'), nullable=True))
    op.drop_column('cluster_meta', 'full_text')
    # ### end Alembic commands ###
