"""empty message

Revision ID: 3279fe550ad8
Revises: 151c1574521e
Create Date: 2019-02-24 13:47:35.551498

"""

# revision identifiers, used by Alembic.
revision = '3279fe550ad8'
down_revision = '151c1574521e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'cluster_meta_ibfk_1', 'cluster_meta', type_='foreignkey')
    op.drop_column('cluster_meta', 'source_cluster')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster_meta', sa.Column('source_cluster', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'cluster_meta_ibfk_1', 'cluster_meta', 'metadata', ['source_cluster'], ['id'])
    # ### end Alembic commands ###
