"""empty message

Revision ID: 80112f16aa04
Revises: 050f6b16fcd8
Create Date: 2019-02-24 13:26:45.443658

"""

# revision identifiers, used by Alembic.
revision = '80112f16aa04'
down_revision = '050f6b16fcd8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_cluster', sa.Integer(), nullable=True),
    sa.Column('nyt_id', sa.String(length=99), nullable=True),
    sa.Column('review_type', sa.String(length=500), nullable=True),
    sa.Column('corrected_transcription', sa.String(length=99999), nullable=True),
    sa.Column('perceived_author_name', sa.String(length=99), nullable=True),
    sa.Column('perceived_author_gender', sa.String(length=99), nullable=True),
    sa.ForeignKeyConstraint(['source_cluster'], ['metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cluster_meta')
    # ### end Alembic commands ###
