"""empty message

Revision ID: 92bf4e96ea9b
Revises: 3279fe550ad8
Create Date: 2019-02-24 14:00:49.622261

"""

# revision identifiers, used by Alembic.
revision = '92bf4e96ea9b'
down_revision = '3279fe550ad8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster_meta', sa.Column('reviewed_work_title', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cluster_meta', 'reviewed_work_title')
    # ### end Alembic commands ###
