"""empty message

Revision ID: ad6aee010c53
Revises: dd5c126d6a4e
Create Date: 2017-11-20 10:31:09.701957

"""

# revision identifiers, used by Alembic.
revision = 'ad6aee010c53'
down_revision = 'dd5c126d6a4e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('common_name', sa.String(length=99), nullable=True))
    op.add_column('author', sa.Column('first_name', sa.String(length=99), nullable=True))
    op.add_column('author', sa.Column('last_name', sa.String(length=99), nullable=True))
    op.add_column('author', sa.Column('viaf_uri', sa.String(length=500), nullable=True))
    op.drop_column('author', 'viaf')
    op.add_column('work', sa.Column('viaf_uri', sa.String(length=500), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work', 'viaf_uri')
    op.add_column('author', sa.Column('viaf', mysql.VARCHAR(collation=u'utf8_bin', length=500), nullable=True))
    op.drop_column('author', 'viaf_uri')
    op.drop_column('author', 'last_name')
    op.drop_column('author', 'first_name')
    op.drop_column('author', 'common_name')
    ### end Alembic commands ###
