"""empty message

Revision ID: dd5c126d6a4e
Revises: None
Create Date: 2017-11-20 09:21:58.901917

"""

# revision identifiers, used by Alembic.
revision = 'dd5c126d6a4e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metadata', sa.Column('review_word_count', sa.Integer(), nullable=True))
    op.drop_index('ix_metadata_byline', table_name='metadata')
    op.drop_index('ix_metadata_document_type', table_name='metadata')
    op.drop_index('ix_metadata_month', table_name='metadata')
    op.drop_index('ix_metadata_nyt_id', table_name='metadata')
    op.drop_index('ix_metadata_page', table_name='metadata')
    op.drop_index('ix_metadata_review_type', table_name='metadata')
    op.drop_index('ix_metadata_word_count', table_name='metadata')
    op.drop_index('ix_metadata_year', table_name='metadata')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_metadata_year', 'metadata', ['year'], unique=False)
    op.create_index('ix_metadata_word_count', 'metadata', ['word_count'], unique=False)
    op.create_index('ix_metadata_review_type', 'metadata', ['review_type'], unique=False)
    op.create_index('ix_metadata_page', 'metadata', ['page'], unique=False)
    op.create_index('ix_metadata_nyt_id', 'metadata', ['nyt_id'], unique=False)
    op.create_index('ix_metadata_month', 'metadata', ['month'], unique=False)
    op.create_index('ix_metadata_document_type', 'metadata', ['document_type'], unique=False)
    op.create_index('ix_metadata_byline', 'metadata', ['byline'], unique=False)
    op.drop_column('metadata', 'review_word_count')
    ### end Alembic commands ###
