"""empty message

Revision ID: 02f64517b8c9
Revises: None
Create Date: 2016-11-30 15:25:07.641685

"""

# revision identifiers, used by Alembic.
revision = '02f64517b8c9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=9999), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policy')
    ### end Alembic commands ###
