"""empty message

Revision ID: 0e67481602ad
Revises: 8fc9c393f516
Create Date: 2016-12-12 15:54:58.611687

"""

# revision identifiers, used by Alembic.
revision = '0e67481602ad'
down_revision = '8fc9c393f516'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basics', sa.Column('github', sa.String(length=500), nullable=True))
    op.add_column('basics', sa.Column('zotero', sa.String(length=500), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('basics', 'zotero')
    op.drop_column('basics', 'github')
    ### end Alembic commands ###
