"""empty message

Revision ID: 33de5bf2bcf0
Revises: a5cf51f9747d
Create Date: 2016-12-24 20:01:08.375781

"""

# revision identifiers, used by Alembic.
revision = '33de5bf2bcf0'
down_revision = 'a5cf51f9747d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('profile_image', sa.String(length=250), nullable=True),
    sa.Column('display_name', sa.String(length=250), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_user_display_name'), 'admin_user', ['display_name'], unique=True)
    op.create_index(op.f('ix_admin_user_email'), 'admin_user', ['email'], unique=True)
    op.create_index(op.f('ix_admin_user_profile_image'), 'admin_user', ['profile_image'], unique=False)
    op.create_index(op.f('ix_admin_user_username'), 'admin_user', ['username'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('github_access_token', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    op.add_column(u'activity', sa.Column('order', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'activity', 'order')
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('profile_image', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('display_name', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('authenticated', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('users')
    op.drop_index(op.f('ix_admin_user_username'), table_name='admin_user')
    op.drop_index(op.f('ix_admin_user_profile_image'), table_name='admin_user')
    op.drop_index(op.f('ix_admin_user_email'), table_name='admin_user')
    op.drop_index(op.f('ix_admin_user_display_name'), table_name='admin_user')
    op.drop_table('admin_user')
    ### end Alembic commands ###
