"""empty message

Revision ID: 76fea4377eda
Revises: 0e67481602ad
Create Date: 2016-12-17 14:19:30.720334

"""

# revision identifiers, used by Alembic.
revision = '76fea4377eda'
down_revision = '0e67481602ad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('text_date', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment', 'text_date')
    ### end Alembic commands ###
