"""empty message

Revision ID: 8fc9c393f516
Revises: 02f64517b8c9
Create Date: 2016-12-11 14:09:42.935857

"""

# revision identifiers, used by Alembic.
revision = '8fc9c393f516'
down_revision = '02f64517b8c9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=9999), nullable=True),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['day.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    ### end Alembic commands ###
