"""empty message

Revision ID: a076c68ee05d
Revises: None
Create Date: 2016-11-12 20:20:53.559427

"""

# revision identifiers, used by Alembic.
revision = 'a076c68ee05d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reading')
    op.drop_table('day')
    op.drop_table('week')
    op.drop_table('user')
    op.drop_table('assignment')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=True),
    sa.Column('submit_instructions', sa.VARCHAR(length=128), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=128), nullable=True),
    sa.Column('link_title', sa.VARCHAR(length=128), nullable=True),
    sa.Column('day_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], [u'day.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.Column('profile_image', sa.VARCHAR(length=128), nullable=True),
    sa.Column('display_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=50), nullable=True),
    sa.Column('password', sa.VARCHAR(length=50), nullable=True),
    sa.Column('authenticated', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('week',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('week_number', sa.INTEGER(), nullable=True),
    sa.Column('week_topic', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('day',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('week_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['week_id'], [u'week.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('page_range', sa.VARCHAR(length=50), nullable=True),
    sa.Column('publisher', sa.VARCHAR(length=50), nullable=True),
    sa.Column('pubdate', sa.VARCHAR(length=50), nullable=True),
    sa.Column('pubplace', sa.VARCHAR(length=50), nullable=True),
    sa.Column('link', sa.VARCHAR(length=50), nullable=True),
    sa.Column('article_title', sa.VARCHAR(length=128), nullable=True),
    sa.Column('book_title', sa.VARCHAR(length=128), nullable=True),
    sa.Column('day_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], [u'day.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
