"""empty message

Revision ID: a5cf51f9747d
Revises: 76fea4377eda
Create Date: 2016-12-21 19:41:04.171712

"""

# revision identifiers, used by Alembic.
revision = 'a5cf51f9747d'
down_revision = '76fea4377eda'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basics', sa.Column('hypoth', sa.String(length=500), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('basics', 'hypoth')
    ### end Alembic commands ###
