"""empty message

Revision ID: 807549d7e45c
Revises: 
Create Date: 2020-01-24 23:37:21.222939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '807549d7e45c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('description', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'description')
    # ### end Alembic commands ###
