"""empty message

Revision ID: 2fd523904a9a
Revises: 5e0d9c43ee78
Create Date: 2016-12-12 15:54:19.811480

"""

# revision identifiers, used by Alembic.
revision = '2fd523904a9a'
down_revision = '5e0d9c43ee78'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basics', sa.Column('github', sa.String(length=500), nullable=True))
    op.add_column('basics', sa.Column('zotero', sa.String(length=500), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('basics', 'zotero')
    op.drop_column('basics', 'github')
    ### end Alembic commands ###
