"""empty message

Revision ID: 5e0d9c43ee78
Revises: 77e252f0d4c0
Create Date: 2016-12-11 14:10:20.808015

"""

# revision identifiers, used by Alembic.
revision = '5e0d9c43ee78'
down_revision = '77e252f0d4c0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=9999), nullable=True),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['day.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    ### end Alembic commands ###
