"""empty message

Revision ID: 77e252f0d4c0
Revises: None
Create Date: 2016-11-30 15:23:03.651464

"""

# revision identifiers, used by Alembic.
revision = '77e252f0d4c0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=9999), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('page_range', sa.String(length=50), nullable=True),
    sa.Column('publisher', sa.String(length=50), nullable=True),
    sa.Column('pubdate', sa.String(length=50), nullable=True),
    sa.Column('pubplace', sa.String(length=50), nullable=True),
    sa.Column('link', sa.String(length=50), nullable=True),
    sa.Column('article_title', sa.String(length=128), nullable=True),
    sa.Column('book_title', sa.String(length=128), nullable=True),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['day.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reading')
    op.drop_table('policy')
    ### end Alembic commands ###
