"""empty message

Revision ID: d24eddc5e40d
Revises: 59163d46a92a
Create Date: 2017-07-04 13:29:30.081829

"""

# revision identifiers, used by Alembic.
revision = 'd24eddc5e40d'
down_revision = '59163d46a92a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_access_token', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'users', 'github_access_token')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'users', sa.Column('github_access_token', mysql.VARCHAR(length=200), nullable=True))
    op.drop_table('tokens')
    ### end Alembic commands ###
