"""empty message

Revision ID: be5f6bc9a954
Revises: 32d910c61aaa
Create Date: 2017-07-05 17:32:05.505011

"""

# revision identifiers, used by Alembic.
revision = 'be5f6bc9a954'
down_revision = '32d910c61aaa'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('public', sa.String(length=128), nullable=True))
    op.add_column('activity', sa.Column('title', sa.String(length=500), nullable=True))
    op.drop_column('basics', 'public')
    op.add_column('policy', sa.Column('public', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policy', 'public')
    op.add_column('basics', sa.Column('public', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('activity', 'title')
    op.drop_column('activity', 'public')
    ### end Alembic commands ###
