"""empty message

Revision ID: 2d0ed130c7bb
Revises: 0c07c66b4c44
Create Date: 2018-12-01 12:07:54.997393

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d0ed130c7bb'
down_revision = '0c07c66b4c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('path', sa.String(length=512), nullable=True))
    op.add_column('blog_post', sa.Column('post_path', sa.String(length=512), nullable=False))
    op.add_column('timeline_entry', sa.Column('entry_teaser', sa.Text(), nullable=False))
    op.drop_column('timeline_entry', 'entry_blurb')
    op.add_column('user_profile', sa.Column('custom_blog_path', sa.String(length=512), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'custom_blog_path')
    op.add_column('timeline_entry', sa.Column('entry_blurb', mysql.VARCHAR(length=4999), nullable=False))
    op.drop_column('timeline_entry', 'entry_teaser')
    op.drop_column('blog_post', 'post_path')
    op.drop_column('blog_post', 'path')
    # ### end Alembic commands ###
