"""empty message

Revision ID: 986649c3e163
Revises: c3a025abb030
Create Date: 2018-12-01 10:32:37.137995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '986649c3e163'
down_revision = 'c3a025abb030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('basics', 'course_description',
               existing_type=mysql.VARCHAR(length=9999),
               nullable=False)
    op.alter_column('policy', 'description',
               existing_type=mysql.VARCHAR(length=9999),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profile_custom_blog_title'), table_name='user_profile')
    op.drop_column('user_profile', 'custom_blog_title')
    op.drop_column('user_profile', 'approved')
    op.alter_column('policy', 'description',
               existing_type=mysql.VARCHAR(length=9999),
               nullable=True)
    op.drop_column('dataset', 'field_notes')
    op.alter_column('basics', 'course_description',
               existing_type=mysql.VARCHAR(length=9999),
               nullable=True)
    # ### end Alembic commands ###
