"""empty message

Revision ID: b1e1a30474cb
Revises: 04bcb668b72f
Create Date: 2018-11-26 13:12:50.949816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1e1a30474cb'
down_revision = '04bcb668b72f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('public', sa.String(length=128), nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('end_month', sa.Integer(), nullable=True),
    sa.Column('end_day', sa.Integer(), nullable=True),
    sa.Column('display_date', sa.String(length=128), nullable=True),
    sa.Column('media', sa.String(length=500), nullable=True),
    sa.Column('media_credit', sa.String(length=128), nullable=True),
    sa.Column('media_caption', sa.String(length=500), nullable=True),
    sa.Column('media_thumbnail', sa.String(length=500), nullable=True),
    sa.Column('entry_type', sa.String(length=128), nullable=True),
    sa.Column('entry_group', sa.String(length=128), nullable=True),
    sa.Column('background', sa.String(length=128), nullable=True),
    sa.Column('entry_blurb', sa.String(length=4999), nullable=False),
    sa.Column('entry_essay', sa.String(length=4999), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeline_entry')
    # ### end Alembic commands ###
