"""empty message

Revision ID: bb961e2552ad
Revises: 
Create Date: 2020-08-08 11:06:52.286360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb961e2552ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('syllabus', sa.Column('lab_schedule', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('syllabus', 'lab_schedule')
    # ### end Alembic commands ###
