"""empty message

Revision ID: 461bb35dc351
Revises: 37c4213f0ceb
Create Date: 2018-12-14 22:48:05.332786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '461bb35dc351'
down_revision = '37c4213f0ceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('custom_blog_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'custom_blog_description')
    # ### end Alembic commands ###
