"""empty message

Revision ID: 5bbe653e85d8
Revises: be5f6bc9a954
Create Date: 2017-07-05 20:02:22.768380

"""

# revision identifiers, used by Alembic.
revision = '5bbe653e85d8'
down_revision = 'be5f6bc9a954'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity', 'description',
               existing_type=mysql.VARCHAR(length=9999),
               nullable=False)
    op.alter_column('activity', 'public',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('activity', 'title',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
    op.alter_column('assignment', 'description',
               existing_type=mysql.VARCHAR(length=9999),
               nullable=False)
    op.alter_column('assignment', 'link_title',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('assignment', 'submit_instructions',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('assignment', 'title',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.add_column('collection', sa.Column('title', sa.String(length=999), nullable=False))
    op.alter_column('collection', 'public',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.drop_column('collection', 'name')
    op.alter_column('collection_items', 'collection_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('collection_items', 'order',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('collection_items', 'target_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('collection_items', 'target_table',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('reading', 'public',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reading', 'public',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('collection_items', 'target_table',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('collection_items', 'target_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('collection_items', 'order',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('collection_items', 'collection_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.add_column('collection', sa.Column('name', mysql.VARCHAR(length=999), nullable=True))
    op.alter_column('collection', 'public',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.drop_column('collection', 'title')
    op.alter_column('assignment', 'title',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('assignment', 'submit_instructions',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('assignment', 'link_title',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('assignment', 'description',
               existing_type=mysql.VARCHAR(length=9999),
               nullable=True)
    op.alter_column('activity', 'title',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
    op.alter_column('activity', 'public',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('activity', 'description',
               existing_type=mysql.VARCHAR(length=9999),
               nullable=True)
    ### end Alembic commands ###
