FROM nginx

COPY key.pem /etc/nginx/key.pem
COPY cert.pem /etc/nginx/cert.pem

COPY privkey.pem /etc/nginx/privkey.pem
COPY fullchain.pem /etc/nginx/fullchain.pem

COPY certs/hum/privkey.pem /etc/nginx/hum/privkey.pem
COPY certs/hum/fullchain.pem /etc/nginx/hum/fullchain.pem
