FROM nginx

COPY privkey.pem /etc/nginx/privkey.pem
COPY fullchain.pem /etc/nginx/fullchain.pem

COPY certs/hum/privkey.pem /etc/nginx/hum/privkey.pem
COPY certs/hum/fullchain.pem /etc/nginx/hum/fullchain.pem

COPY certs/comp/privkey.pem /etc/nginx/comp/privkey.pem
COPY certs/comp/fullchain.pem /etc/nginx/comp/fullchain.pem



