FROM nginx

COPY certs/ml/privkey.pem /etc/nginx/ml/privkey.pem
COPY certs/ml/fullchain.pem /etc/nginx/ml/fullchain.pem

COPY certs/hum/privkey.pem /etc/nginx/hum/privkey.pem
COPY certs/hum/fullchain.pem /etc/nginx/hum/fullchain.pem

COPY certs/comp/privkey.pem /etc/nginx/comp/privkey.pem
COPY certs/comp/fullchain.pem /etc/nginx/comp/fullchain.pem

COPY certs/bh/privkey.pem /etc/nginx/bh/privkey.pem
COPY certs/bh/fullchain.pem /etc/nginx/bh/fullchain.pem

COPY certs/rml/privkey.pem /etc/nginx/rml/privkey.pem
COPY certs/rml/fullchain.pem /etc/nginx/rml/fullchain.pem
