"""empty message

Revision ID: 088886aa583f
Revises: 461bb35dc351
Create Date: 2018-12-21 12:17:53.382929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088886aa583f'
down_revision = '461bb35dc351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('static_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('public', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('route', sa.String(length=512), nullable=False),
    sa.Column('page_data', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('static_page')
    # ### end Alembic commands ###
