"""empty message

Revision ID: 12ef1fab3f81
Revises: 1aa49751e359
Create Date: 2020-02-17 12:19:48.501985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ef1fab3f81'
down_revision = '1aa49751e359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extracted_parsed', sa.Column('reviewed_book_publisher_viaf_match', sa.String(length=256), nullable=True))
    op.add_column('review', sa.Column('reviewed_book_publisher_viaf_match', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'reviewed_book_publisher_viaf_match')
    op.drop_column('extracted_parsed', 'reviewed_book_publisher_viaf_match')
    # ### end Alembic commands ###
