"""empty message

Revision ID: 1aa49751e359
Revises: 
Create Date: 2020-01-31 10:10:11.378247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aa49751e359'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('last_edited', sa.String(length=128), nullable=True))
    op.add_column('review', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'review', 'user_profile', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_column('review', 'user_id')
    op.drop_column('review', 'last_edited')
    # ### end Alembic commands ###
