"""empty message

Revision ID: 645a146ab428
Revises: 12ef1fab3f81
Create Date: 2020-02-21 11:58:19.425740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645a146ab428'
down_revision = '12ef1fab3f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cross_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_ids', sa.String(length=5121), nullable=True),
    sa.Column('target_ids', sa.String(length=5121), nullable=True),
    sa.Column('comparison_size', sa.Integer(), nullable=True),
    sa.Column('author_name_distance', sa.Integer(), nullable=True),
    sa.Column('author_name_number', sa.Integer(), nullable=True),
    sa.Column('author_gender_cohen_kappa', sa.Float(), nullable=True),
    sa.Column('author_viaf_cohen_kappa', sa.Float(), nullable=True),
    sa.Column('publisher_viaf_cohen_kappa', sa.Float(), nullable=True),
    sa.Column('pub_date_difference', sa.Integer(), nullable=True),
    sa.Column('genre_cohen_kappa', sa.Float(), nullable=True),
    sa.Column('price_cohen_kappa', sa.Float(), nullable=True),
    sa.Column('book_title_distance', sa.Integer(), nullable=True),
    sa.Column('truncated_book_title_distance', sa.Integer(), nullable=True),
    sa.Column('review_type_cohen_kappa', sa.Float(), nullable=True),
    sa.Column('experiment', sa.String(length=256), nullable=True),
    sa.Column('annotation', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cross_check')
    # ### end Alembic commands ###
