"""empty message

Revision ID: ddf8b7e193f7
Revises: eade3461afd3
Create Date: 2016-11-13 11:01:00.013453

"""

# revision identifiers, used by Alembic.
revision = 'ddf8b7e193f7'
down_revision = 'eade3461afd3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basics', sa.Column('course_description', sa.String(length=9999), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('basics', 'course_description')
    ### end Alembic commands ###
